### ISSUE TITLE
timezone vs time_zone

### ISSUE THREAD

**Issue by linville** [acockburn/appdaemon#1]
Home assistant uses "time_zone" in it's [configuration file](https://github.com/home-assistant/home-assistant/blob/9afb1d8c0dbacf3f36e3ea6d6513bcd7e13be242/homeassistant/config.py#L42). Current AppDaemon uses "timezone". It would probably be nice for AppDaemon to be consistent with Home Assistant's syntax.

**Comment by acockburn** [comment]
Can't argue with that - I'll add it to the next version.

**Comment by acockburn** [comment]
Fixed.
