### ISSUE TITLE
Feature Request - Recursively monitor apps folder

### ISSUE THREAD

**Issue by jbardi** [acockburn/appdaemon#10]
Thought about posting this in the HA community thread, but I thought it might get lost. In HA, I have each of my automations in separate files, organized in subfolders. I am on a roll making lots of apps, so it would be great if we could organize them in subfolders under the apps direction and have it monitor recursively to pickup all new apps instead of having them all out in the root of the apps directory.

**Comment by acockburn** [comment]
Yes, multiple APP dirs is something I have thought about a couple of times, although I didn't think of making the search recursive - either way it should be doable - I'll add it to the list for my next version.

**Comment by acockburn** [comment]
OK, just pushed an update with this feature.

**Comment by jbardi** [comment]
Wow, that was a quick response, thanks.

I went ahead and updated, but it still doesn't read any of my apps from subfolders. If I put stop appdaemon and move them all to subfolders from the root of the apps directory, then restart, the log just shows "INFO Got initial state" but nothing about loading any of the apps. Then if I make a change to the appdaemon.cfg to force a reload, I get a "ImportError: No module named mymodule" or whatever the name of my module is. But if I then move it back to root and make a change to appdaemon.cfg to reload again it them finds it no problem, so it still doesn't seem to be looking beyond the root of the apps folder.

**Comment by acockburn** [comment]
Works fine here - how do you upgrade?  I am doing the following:

$ pip3 uninstall appdaemon
$ pip3 install .

**Comment by jbardi** [comment]
Oh I am sooo sorry!  All I did was $ git pull origin

I completely forgot that with the new version I have to use pip after pulling the update... It works now perfectly!

Thank you so much! With the recursively folders, now everything is perfect! You are the king!!!

**Comment by acockburn** [comment]
Great, glad you are still liking it :) I should add the git piece to the read me I guess.

**Comment by jbardi** [comment]
Yeah, thats what threw me... I just scrolled to the bottom of the git readme to the "Updating AppDaemon" section because I forgot how to update, and that was all that was there.
