### ISSUE TITLE
Listening for an event with specific data

### ISSUE THREAD

**Issue by cmsimike** [acockburn/appdaemon#13]
Hi,

I am loving this functionality! Thank you very much for making it so easy to have very complex automations :D!

I was trying out a custom automation using my zwave minimote. The tl;dr about it is that it is a multi-button remote. When a button is pressed, it emits an event, zwave.scene_activated, and it also associates some data about which button was pressed in the form of scene_id in an object:

```
2016-09-07 22:19:11.654286 DEBUG Event type:zwave.scene_activated:
2016-09-07 22:19:11.654432 DEBUG {'object_id': 'aeotec_dsa03202_minimote_4', 'entity_id': 'aeotec_dsa03202_minimote_4', 'scene_id': 7}
```

I am currently listening for events like this:
```
self.listen_event(self.cycle_scene, 'zwave.scene_activated', entity_id='aeotec_dsa03202_minimote_4')
```

I had originally thought that by passing another named parameter, scene_id, I'd be able to automatically filter on that.
```
self.listen_event(self.cycle_scene, 'zwave.scene_activated', entity_id='aeotec_dsa03202_minimote_4', scene_id=self.scene_id)
```

However, that did not work and cycle_scene was called for each different button press.

I'm currently getting around this by persisting a configured scene_id in initialize, and in the callback method, checking the incoming data and aborting the action if the numbers do not match:
```
  def cycle_scene(self, event_name, data, kwargs):
      if 'scene_id' in data and int(data['scene_id']) != int(self.scene_id):
          self.log('done')
          return

      # other code removed
```

Not bad, but I'm wondering if I've just missed something in the docs about how better to deal with this?

Thanks

**Comment by acockburn** [comment]
Hi there - that's about as good as you can get with current functionality - unlike `listen_state()`, `listen_event()` is pretty simple, it responds to the named event and hands the data over.

This is partly because I haven't had a more complex usecase - I use custom events myself, but only in a simple way. However, there is no reason I couldn't expand it to handle the usecase of listening for specific attributes as is possible in `listen_state()` - to be somewhat consistent with `listen_state()` I would probably do something like:

```python
self.listen_event(self.cycle_scene, 'zwave.scene_activated', attribute="scene_id", value=self.scene_id)
```

Does that sound like it would work?

FWIW, I have a minimote too but haven't gone through the hassle of setting it up for HA yet, so maybe I will do so so I can test this feature :)

**Comment by cmsimike** [comment]
That sounds perfect! Thank you very much :D

**Comment by acockburn** [comment]
OK, I will add it to the list, but for now you have a working setup :)

**Comment by acockburn** [comment]
Got my minimote working and I have added filtering to the listen state call - it has info in the API file but here are a couple of examples of what I ended up with:

# Listen for a minimote event activating scene 3:
self.listen_event(self.generic_event, "zwave.scene_activated", scene_id = 3)
# Listen for a minimote event activating scene 3 from a specific minimote:
self.listen_event(self.generic_event, "zwave.scene_activated", entity_id = "minimote_31", scene_id = 3)

I am calling these "event filters" and you can use them to filter for any arguments in any event.

I am just about to push the release with this in - 1.3.3.

**Comment by cmsimike** [comment]
Thank you so much for this! (Sorry for the delay - circling back to automation stuff now).
Looking forward to cleaning up the code I have.
