### ISSUE TITLE
Connecting with SSL enabled: Option to specify root CA certificate

### ISSUE THREAD

**Issue by siam28** [acockburn/appdaemon#14]
Thanks for this immensely helpful extension to HASS.
I am connecting with SSL enabled with a self-signed certificate.
To do this, I made changes in the source files so that all references to `requests.get` includes a `verify` option. 

For instance:
``r = requests.get(apiurl, headers=headers, verify="/path/to/root/CA/cert")``

Would it be possible to add an option for a root CA certificate file in the config file?

**Comment by acockburn** [comment]
Should be an easy fix - what happens if you use a self signed cert and you don't include the path?

**Comment by acockburn** [comment]
I coded this into the latest version which I will release in the next day or so. I haven't been able to test it so I will rely on you to let me know if it works!
