### ISSUE TITLE
python package for pip install

### ISSUE THREAD

**Issue by justyns** [acockburn/appdaemon#3]
The installation instructions are pretty manual right now; it'd help if the project was set up as a normal pip-installable python package.  Even just adding a setup.py should allow people to pip install it using the git url.

Adding a `requirements.txt` and changing the instructions to `pip3 install -r requirements.txt` would also be a good improvement over manually installing multiple dependencies.

**Comment by acockburn** [comment]
Couldn't agree more - I am relatively new to Python and haven't done any of the above previously but I will add this to the next release. FWIW I am also working on a Docker file.

**Comment by MartinHjelmare** [comment]
@acockburn Do you want a PR for the python package structure, or do you want to do it yourself? I have a branch more or less ready.

**Comment by acockburn** [comment]
I really appreciate you working on it but I regard this as a learning process and would really like to figure it out myself - perhaps I could ask you for feedback when I have something?

**Comment by MartinHjelmare** [comment]
Good call! I'm happy to answer questions as far as I'm able. I've pushed my branch to my fork, so you can take a look if you like when you're ready. I suggest reading some docs or blog first, though.

There is also the cookiecutter project which can setup a full project skeleton for you with optional test modules, travis, tox and pypi scripts.

**Comment by acockburn** [comment]
Thanks for the pointers - I can forsee a lot of reading this weekend :)

**Comment by justyns** [comment]
I'll second @MartinHjelmare; if you need any help/feedback feel free to let me know too!

**Comment by acockburn** [comment]
Thanks, much appreciated!

**Comment by jasonmhite** [comment]
A note on this one... assuming you build a package such that it installs an executable to the standard system path (e.g. via the [scripts](http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-scripts-keyword-argument) argument to `setup`), that will make it much easier to write initscripts since you can rely on `appdaemon` being in `$PATH`.

I can contribute a systemd unit file to go alongside the existing initscript once it's done, it's only about 5 lines. I have one now that I'm using on Debian, but if AppDaemon is going to get packaged up I might as well wait.

**Comment by acockburn** [comment]
Makes sense - I would like to have a look at your systemd script.

**Comment by acockburn** [comment]
OK, this is done - thanks Martin for your example (which I pretty much used) as well as the additional assistance in answering my questions.

@jasonmhite - as currently constructed, an `appdaemon` executable is made available in "/usr/local/bin", at least that's where it ends up on Ubuntu, so in the path as requested.

**Comment by timdonovanuk** [comment]
Is appdaemon supposed to be easy to install using pip? I've just spent the last 30 minutes running appdaemon, seeing what "ImportError: No module named '<foobar>' it gives this time, and then running pip to manually install the missing package. No end in sight either. Feel like I'm missing something. http://appdaemon.readthedocs.io/en/latest/INSTALL.html also has a few 404 links (Docker link, HA link).

**Comment by acockburn** [comment]
It should be a single command - with possibly a couple of apt-get installs listed in the docs.

**Comment by timdonovanuk** [comment]
Ah! My apologies...maybe move that section up a bit...listing dependencies required to get something working right at the bottom of documentation is a little..unusual!

**Comment by acockburn** [comment]
I can certainly do that :)

**Comment by timdonovanuk** [comment]
Thanks! Confirmed all working happily now :)

**Comment by acockburn** [comment]
Great :)
