### ISSUE TITLE
Allow logging to stdout and stderr

### ISSUE THREAD

**Issue by jasonmhite** [acockburn/appdaemon#4]
I'm managing AppDaemon via a systemd unit on Debian 8. The easiest way to do this is to actually not use the daemonize option and instead to run in the foreground. Systemd then handles managing the process and its children and also automatically captures stderr and stdout to the system log.

Currently when running in the foreground, log messages go stderr and errors get put into a `RotatingFileHandler` controlled by the `errorfile` config setting. It would be very convenient if I could set it to dump regular messages to stdout and errors to stderr, so that I can just let systemd handle organizing the logs; I'm on a RasPi and want to avoid writing to the filesystem (and have systemd configured to save logs in memory), plus it's handy to be able to view the logs with messages and errors colorized properly with `systemctl status`. 

To this end, I have a pull request where I have made a couple small changes. Basically, if you are running in the foreground and you have `logfile = STDOUT` in the configuration, then standard log messages will go to stdout. Similarly, if you have `errorfile = STDERR` then errors go to stderr. Finally, if you have both set, then it also suppresses the log messages that mention when an error has been logged (since you're going to see it in the output).

I did this in a way that I think won't break anything. For one, if called with `--daemonize` these checks are bypassed. Also, the previous behavior is preserved and this only kicks in when passing STDOUT or STDERR.

Let me know if you would prefer that it is implemented differently and I can change it.

**Comment by acockburn** [comment]
Thanks for the PR I'll take a look soon - as long as it doesn't break previous behavior (e.g. logs to the terminal when running without Daemonize I think it is a good addition, especially given the detailed usecase you gave me :)

**Comment by acockburn** [comment]
PR Merged
