### ISSUE TITLE
Connecting with SSL enabled

### ISSUE THREAD

**Issue by tkwatson63** [acockburn/appdaemon#6]
When I set HA and AppDaemon to use http everything works just fine. When I change over to using SSL AppDaemon is unable to connect to HA. I am using a self signed certificate with HA, is this a problem?

**Comment by acockburn** [comment]
I think this was answered in the forums but I will levae this open as a reminder to improve the error reporting in that particular situation

**Comment by acockburn** [comment]
Error reporting for initial connect has been improved.
