### ISSUE TITLE
Systemd unit and standardizing the configuration location

### ISSUE THREAD

**Issue by jasonmhite** [acockburn/appdaemon#8]
Per discussion from #3...

The unitfiles for systemd are pretty simple, assuming appdaemon is executable and in $PATH then it's just something like

```
[Unit]
Description=AppDaemon service for Home Assistant

[Service]
ExecStart=/usr/bin/appdaemon /path/to/config

[Install]
WantedBy=multi-user.target
```

This would be `appdaemon.service` and gets dropped in `/etc/systemd/system`.

As a side note, you might want to set a default location for the configuration file like `/etc/appdaemon/appdaemon.cfg` or something. That way you don't need to pass the name of the config file in the service call (same applies to sysv init scripts). The end goal in my mind being that AppDaemon can behave like most daemons and use standard paths so the user doesn't have to edit the service files to set paths.

Once you merge your changes to repackage AppDaemon I can test and add the unit file. Lemme know your opinions on standardizing the config file location, I can do the work there too but it's your call on if/how to do it.

**Comment by acockburn** [comment]
Hi there  - taking a look at this now that I have done docker and pip3 installation. I am thinking the following for the config:

1. If a config file is specified, use that
2. Check fo /etc/appdaemon/appdaemon.cfg
3. Check fo ~/.homeassistant/appdaemon.cfg

Also, check for an apps subdirectory in the same places. if not explicitly specified.

**Comment by acockburn** [comment]
OK - all done - will be pushing a release later on today.

**Comment by jasonmhite** [comment]
Awesome, I migrated to the new version packaged with setuptools and switched to the "official" systemd unit. All seems to be working quite smoothly!
