### ISSUE TITLE
Problems upgrading from the Initial v1 release

### ISSUE THREAD

**Issue by jbardi** [acockburn/appdaemon#9]
There were several issues with upgrading from the initial release that broke everything until I did some trial and error troubleshooting.

A big issue was that you changed from using import appapi to import appdaemon.appapi as appapi, which stopped all of my pervious apps from running. I only found out the proper import by looking at the hello.py, so I had to replace that line in all of my apps.

I was forced to run it as a systemd service because the /etc/init.d script you provided will not work as it keeps giving the error:

ImportError: No module named 'appdaemon.conf'; 'appdaemon' is not a package

So it is not finding the conf.py from the appdaemon.py

So, then, using the systemd service throws an error because it does not include the -c argument to point to the configuration file, which is at the default location along with the included appdaemon.cfg.example, but it still told me it couldn't find it, so I had to add the -c flag to the appdaemon.service file.

I really LOVE appdaemon, but enough has changed from the setup of the original version that I can guarantee that all users of the previous version will have errors and problems upgrading. Hopefully this will not be a problem for new users starting out fresh.

Thanks again for the appdaemon, don't know how I lived without it :)

**Comment by acockburn** [comment]
Hi there - thanks for the feedback - I did mention some of these points in the History file and also in the post where I announced the upgrade - particularly the change to the import.

I'll take a look at the init script - I just moved to the systemd script (I have my stuff in the default path) so it worked for me and the init script obviously needs a tweak.

**Comment by acockburn** [comment]
Pushed a new version of the INIT script that should work now and I also updated the systemd unit file with instructions on using the -c option if required.
